feat : 도메인 작성
next-step/career-architecture pull request #2
Opened 2023-12-08 02:28 UTC by qotjsry

안녕하세요
저희 회사 도메인이 주차관제시스템인데
이게 간략한 플로우로는 입차 -> 요금정산 -> 출차 이지만
하나의 솔루션을 SI 형식으로 수백개 사이트에 설치하다 보니 각 사이트별 많은 옵션과 특정사이트만 필요한 기능이 들어가서
도메인을 어떻게 그려야 할지 좀 난감합니다.
조언 부탁드리겠습니다.

2023-12-08 22:10 UTC, brainbackdoor commented
궁금한게 몇가지 있는데요.
1. 각 사이트별로 관리하는 저장소가 다른가요? (코드가 상이한가요?)
2. 아니라면, 사이트별 옵션 및 기능은 어떻게 관리하나요? 사이트와 관련된 정보를 배포시 프로퍼티로 관리하고, 코드상에서 if 조건 분기가 있는건가요? 아니면 사이트별 옵션에 대한 정보를 DB로 관리하나요?
3. 이번에 개선하고 싶은 작업은 작성하신 "개선포인트"가 맞지요? 사이트별 옵션 관리는 대상이 아니지요?

2023-12-08 22:29 UTC, brainbackdoor requested changes
2주차 미션 진행하느라 고생하셨어요~ 👍🏻 
잘 진행해주셨는데요, 몇가지 궁금한 점이 있어 Request Changes 했어요~ 
주말 잘 보내세요~

2023-12-08 22:29 UTC, brainbackdoor commented on tobe/ARCHITECTURE-qotjsry.md
> +    ```
```suggestion
```
```

2023-12-08 22:29 UTC, brainbackdoor commented on tobe/ARCHITECTURE-qotjsry.md
> +    H --> M(요금 계산)
1. A의 요금계산과 M의 요금계산은 다른 건가요? 가령, 전자는 "요금계산 요청"과 같은 Command인가요? 아니면 요금계산을 두번 수행하는건가요?
2. 개선된 프로세스에는 "예약차량 포인트 사용 확인"과 "영업용 무료 차량 확인"이 보이지 않는데, 혹시 어떤 의미일까요..?

2023-12-08 22:29 UTC, brainbackdoor commented on tobe/ARCHITECTURE-qotjsry.md
> +- 가장 복잡한 요금계산 로직부터 디자인패턴을 적용하여 개선
1. 어떤 디자인패턴을 고려하고 계신가요?
2. 추상화하여 if 조건 분기를 숨길 경우, 팀원들이 코드를 해석하거나 디버깅할 역량을 갖추고 있나요? 
3. 절차지향적인 프로그래밍이 반드시 코드 분석 시간을 늘리지는 않은데요. 가령, 너무 많은 클래스로 분리되어 있을 경우에 이를 탐색하는데 시간이 더 오래 걸릴수도 있어서요. OOP에 앞서, 메서드 분리와 적절한 네이밍 등 코드 가독성을 높이기 위한 리팩토링이 진행되어 있나요?
4. Controller에 비즈니스 로직이 위치해 있는 별도의 이유가 있나요?
5. 테스트코드가 작성되어 있나요?
6. 개선 포인트 4가지 항목이 아래 기술한 프로세스에 모두 해당하는 내용인가요?
7. 아키텍쳐 개선은 지난번에 말씀드렸듯, 서비스 영향도가 낮고 독립적인 구성요소부터 진행하는 것이 좋습니다. 그 코드를 기반으로 팀원들에게 소개하고 앞으로 점진적으로 어떤 전략으로 리팩토링해나갈 것인지 가이드하는 것이 좋다고 생각합니다.

2023-12-09 05:13 UTC, qotjsry commented on tobe/ARCHITECTURE-qotjsry.md
> +    H --> M(요금 계산)
1. 요금계산 요청 Command입니다. 수정하겠습니다. 
2. 개선된 프로세스에서는 차량주차종류별로 모든 차량이 확인하는게 아닌 예약차량만 예약차량 포인트 사용 확인을 하고 영업용차량만 영업용무료차량확인을 한다는 의미로 그렸습니다. D --> I(예약차량 포인트 사용 확인)
    E --> J(영업용 무료 차량 확인)

2023-12-12 12:54 UTC, qotjsry commented on tobe/ARCHITECTURE-qotjsry.md
> +- 가장 복잡한 요금계산 로직부터 디자인패턴을 적용하여 개선
1. 디자인패턴이라고 거창하게 적었지만 결국 전략패턴과 퍼사드패턴 팩토리 패턴정도를 사용하여 코드를 경량화 할거 같습니다.
2. 현재 if else의 과도한 중첩과 중복소스로 불편함이 더 크다고 생각하여 팀원들 동의하에 리팩토링 예정중입니다.
3. 네이밍과 코드 가독성을 높이기 위한 메서드 분리 작업은 진행 하였습니다.
4. 기존에 만들었던 개발자가 그냥 이유없이 그곳에 넣었다고 들었습니다.
5. 테스트코드는 하나도 작성되어 있지 않아 리팩토링하려는 부분관련해서 테스트코드를 작성하려고 하고 있습니다.
6. 프로세스를 작성하는것이 좀 애매한것 같습니다.

해당 코드 안에 조건이나 중간 분기가 절차적으로 있어 도메인 로직을 어떻게 그려야 할지 감이 잡히지 않습니다. 
입차 - 요금계산 - 출차
기본 로직에 요금계산 로직 안에서 할인에 관련된 로직을 제외 하더라도 많은 사이트가 동일한 코드를 사용하여 해당 로직안에 모든 조건이 녹아 있습니다. 해당 부분을 어떻게 표현하면 될지 조언 부탁드리겠습니다.

2023-12-13 19:58 UTC, brainbackdoor commented on tobe/ARCHITECTURE-qotjsry.md
> +- 가장 복잡한 요금계산 로직부터 디자인패턴을 적용하여 개선
넵~ 리팩토링을 진행하려면, 우선 테스트코드는 필수라고 생각합니다. 그렇지 않으면 잘 돌아가는 서비스에 영향을 주는 상황이 될 수 있으니까요~

---

지금 도메인 모델링, 시스템 아키텍쳐 등을 작성하는게, 완벽한 답을 모색하라는 것은 아니에요.
현재 코드에 중복코드가 많다면, 로직 역시 중복 로직들이 모두 표현되는게 맞습니다. 절차지향적으로 작성되어 있다면 절차지향적으로 표현되는게 맞습니다. 그리고 리팩토링 범위가 커서 어떻게 객체 설계를 해야 할지 모르겠다면, 당연히 개선할 수 있을만큼만 TO-BE로 표현하는게 맞다고 생각해요.
그래야 리팩토링을 어떤 단위로 진행해야 할지 파악해나갈 수 있으니까요

2023-12-13 19:59 UTC, brainbackdoor approved these changes
Comment 확인했어요~ 
미션 진행하느라 고생하셨어요~

2023-12-13 20:01 UTC, merged